### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zarkness** [MediusEcho/ParticleHats#12] opened 2022-09-01 10:16 UTC
Hi, I was wondering if you had a discord group to ask for support.

**Comment by MediusEcho** [comment] 2022-09-01 17:32
Not currently. You can ask for support here or on the Spigot discussion [page](https://www.spigotmc.org/threads/particlehats.27893/)

**Comment by Zarkness** [comment] 2022-09-01 19:58
ok, thank you very much, by the way could you fix the option that when doing shift plus right click deletes the particle that you have equipped? also how do I put particles to the different projectiles that has minecraft, which would be nive balls, among others, to the fishing rod, when you place a block, when you break it, put a particle to a block, when I hit with the sword etc ....

summarizing the things that this plugin does plus some new ones https://www.spigotmc.org/resources/playerparticles.40261/ is that I'm trying your plugin and I liked it a lot more than that one and you seem to be a better dev than the ones in that plugin.

**Comment by Zarkness** [comment] 2022-09-01 19:58
ok, thank you very much, by the way could you fix the option that when doing shift plus right click deletes the particle that you have equipped? also how do I put particles to the different projectiles that has minecraft, which would be nive balls, among others, to the fishing rod, when you place a block, when you break it, put a particle to a block, when I hit with the sword etc ....

summarizing the things that this plugin does plus some new ones https://www.spigotmc.org/resources/playerparticles.40261/ is that I'm trying your plugin and I liked it a lot more than that one and you seem to be a better dev than the ones in that plugin.

**Comment by Zarkness** [comment] 2022-09-01 19:59
ok, thank you very much, by the way could you fix the option that when doing shift plus right click deletes the particle that you have equipped? also how do I put particles to the different projectiles that has minecraft, which would be nive balls, among others, to the fishing rod, when you place a block, when you break it, put a particle to a block, when I hit with the sword etc ....

summarizing the things that this plugin does plus some new ones https://www.spigotmc.org/resources/playerparticles.40261/ is that I'm trying your plugin and I liked it a lot more than that one and you seem to be a better dev than the ones in that plugin.

**Comment by MediusEcho** [comment] 2022-09-01 21:18
> could you fix the option to do shift plus right click to delete the particle you have equipped?
I could not find an issue with the shift right click to delete option. Are you using it in the Equipped Particles Menu (/h particles)?

> how do I put particles to the different projectiles that has minecraft, which would be nive balls, among others, to the fishing rod, when you place a block, when you break it, put a particle to a block, when I hit with the sword, trident and put you need a permit for each particle etc....
The only options for particles right now is players and arrow trails. This is a limitation of how the plugin was designed. I'm currently in the process of rewriting the plugin so that it will be much more flexible with how particles are spawned, though I don't have any estimates to when that will happen.

> summarizing the things that this plugin does plus some new ones https://www.spigotmc.org/resources/playerparticles.40261/ is that I'm trying your plugin and I liked it a lot more than that one and you seem to be a better dev than the ones in that plugin.
Thank You, I'm glad you like the plugin,

**Comment by Zarkness** [comment] 2022-09-02 07:25
> > could you fix the option to do shift plus right click to delete the particle you have equipped?
> 
> I could not find an issue with the shift right click to delete option. Are you using it in the Equipped Particles Menu (/h particles)?

I usually access by putting /h and once the menu opens I hit the head that says show equipped Particles, I do shift + right click as it says and it does not delete it.

> > how do I put particles to the different projectiles that has minecraft, which would be nive balls, among others, to the fishing rod, when you place a block, when you break it, put a particle to a block, when I hit with the sword, trident and put you need a permit for each particle etc....
> 
> The only options for particles right now is players and arrow trails. This is a limitation of how the plugin was designed. I'm currently in the process of rewriting the plugin so that it will be much more flexible with how particles are spawned, though I don't have any estimates to when that will happen.

Ok, I hope the update doesn't take 4 months or so, but if you are rewriting it to be much more flexible then I will wait for the update.

> > summarizing the things that this plugin does plus some new ones https://www.spigotmc.org/resources/playerparticles.40261/ is that I'm trying your plugin and I liked it a lot more than that one and you seem to be a better dev than the ones in that plugin.
> 
> Thank You, I'm glad you like the plugin,

I was looking for a plugin that is well done and I finally found it.

**Comment by MediusEcho** [comment] 2022-09-03 02:23
> I usually access by putting /h and once the menu opens I hit the head that says show equipped Particles, I do shift + right click as it says and it does not delete it.

I followed your steps and was still unable to reproduce the bug. Are you using the latest version? (4.2.16). I'm not sure what else could be causing this issue. 

> Ok, I hope the update doesn't take 4 months or so, but if you are rewriting it to make it much more flexible then I will wait for the update, how long do you think it will take to finish the update?

I don't have a timeline for when the update will be released. I work on the plugin in my free time in-between other projects.

**Comment by Zarkness** [comment] 2022-09-04 08:55
> > I usually access by putting /h and once the menu opens I hit the head that says show equipped Particles, I do shift + right click as it says and it does not delete it.
> 
> I followed your steps and was still unable to reproduce the bug. Are you using the latest version? (4.2.16). I'm not sure what else could be causing this issue.

ok, it's my thing, it must be some mod that I use that must give incompatibility, in case you want to investigate what can be the cause I leave you a .zip with the mods plus the config of them, the version I use is fabric 1.19.2
[Mods fabric.zip](https://github.com/MediusEcho/ParticleHats/files/9484310/Mods.fabric.zip)

> > Ok, I hope the update doesn't take 4 months or so, but if you are rewriting it to make it much more flexible then I will wait for the update, how long do you think it will take to finish the update?
> 
> I don't have a timeline for when the update will be released. I work on the plugin in my free time in-between other projects.

Ok, so then it's a wait and see

**Comment by Zarkness** [comment] 2022-09-04 09:10
I'm redoing it, with new plugins, if I see that it gives me a problem again, if you want I'll send you the new one.

**Closed** 2023-04-25 22:29 UTC
